services:
  - type: web
    name: laravel-filament-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: tu-host-de-render
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: nombre_de_tu_db
      - key: DB_USERNAME
        value: tu_usuario
      - key: DB_PASSWORD
        value: tu_contraseña
